Cadastro de um novo autor
danigfavero/nossa-casa-codigo pull request #1
Opened 2020-02-26 15:14 UTC by danigfavero

Adiciona a funcionalidade de registrar um novo autor no sistema.

2020-02-26 22:48 UTC, asouza requested changes
Só faltou verificar se o nome foi passado... Tirando isso ta tudo certo. Em vez de criar as classes você mandou vários try catch na mesma... mandou bem. Sempre temos espaço para criatividade :). 

Deixei algumas observações, mas o código ficou legal. Simples e direto ao ponto. Protegeu a borda ali no construtor.. Neste momento autores não podem ser criados com informações erradas.

2020-02-26 22:48 UTC, asouza commented on Autor.java
> +class Autor {
tudo bem não deixar a clássica pública por enquanto. Já que você só está usando a ela a partir do main dentro dela :). Mas lembra que outro pacote não veria

2020-02-26 22:48 UTC, asouza commented on Autor.java
> +    String nome;
Já o atributo você pode ser ainda mais restritiva... pode deixar privado mesmo.

2020-02-27 15:54 UTC, danigfavero commented
> Só faltou verificar se o nome foi passado... Tirando isso ta tudo certo. Em vez de criar as classes você mandou vários try catch na mesma... mandou bem. Sempre temos espaço para criatividade :).

De que forma eu deveria checar se o nome foi passado? Afinal só o fato de o construtor pedir o argumento "Nome", já é garantido que alguma String vai ser passada, se não o objeto nem é criado...

2020-02-28 15:47 UTC, asouza approved these changes

2020-02-28 17:17 UTC, merged