Email do autor é único
danigfavero/nossa-casa-codigo pull request #2
Opened 2020-02-28 17:08 UTC by danigfavero

Garante que não haja autores repetidos na coleção de autores (dois autores são iguais se eles tiverem o mesmo email).

2020-02-29 00:17 UTC, asouza requested changes

2020-02-29 00:17 UTC, asouza commented on Autores.java
> +	private static boolean emailsIguais(Autor autor1, Autor autor2) {
Aqui, meu cartão está mal escrito e direciona para um código olhando direto para o email. A ideia é não permitir dois autores iguais. E dois autores são iguais se eles têm o mesmo email. Você pode usar o equals do autor mesmo.

2020-02-29 00:17 UTC, asouza commented on Autores.java
> +public class Autores extends LinkedList<Autor> {
Um desafio... Aqui, quando você herda, você é obrigada a sobreescrever todos os comportamentos de adição, pq agora tem que respeitar a regra. Só que vários deles não são usados.. ```addAll, add(index,element)```. Como você pode fazer para continuar usando uma LinkedList, só que sem herdar?

2020-03-02 15:40 UTC, danigfavero commented on Autores.java
> +public class Autores extends LinkedList<Autor> {
Eu poderia fazer a LinkedList ser um atributo e criar métodos pra encapsular o uso dos métodos da LinkedList? É uma boa ideia?

2020-03-02 20:31 UTC, asouza commented
Ótima!

Em seg, 2 de mar de 2020 12:40, Daniela Favero <notifications@github.com>
escreveu:

> *@danigfavero* commented on this pull request.
> ------------------------------
>
> In Autores.java
> <https://github.com/danigfavero/nossa-casa-codigo/pull/2#discussion_r386469319>
> :
>
> > @@ -0,0 +1,67 @@
>
> +import java.util.Collection;
>
> +import java.util.LinkedList;
>
> +
>
> +public class Autores extends LinkedList<Autor> {
>
>
> Eu poderia fazer a LinkedList ser um atributo e criar métodos pra
> encapsular o uso dos métodos da LinkedList? É uma boa ideia?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/danigfavero/nossa-casa-codigo/pull/2?email_source=notifications&email_token=AAAH6AQCSDFGTEVQLUD3JKLRFPHPVA5CNFSM4K5UQSN2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCXSIODY#discussion_r386469319>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAH6AQKSR5CRJFIUNUNJ33RFPHPVANCNFSM4K5UQSNQ>
> .
>

2020-03-03 16:42 UTC, merged