Exibir a página de detalhe de um livro
danigfavero/nossa-casa-codigo pull request #7
Opened 2020-03-10 22:54 UTC by danigfavero

Criação de página com as mesmas informações que encontramos na página de detalhe da Casa do Código.

2020-03-11 03:39 UTC, asouza requested changes
Está ótimo! Só deixei dois questionamentos.

2020-03-11 03:39 UTC, asouza commented on Livros.java
> +		for (Livro livro : livros) {
Ficou ótimo aqui! Uma sugestão... Será que não podemos usar um Map aqui dentro dessa classe Livros? Ele serviria como uma espécie de índice para você buscar o autor pelo título. Pensa e vê o que acha :)

2020-03-11 03:39 UTC, asouza commented on TestePagina.java
> +        	System.out.println(livroBuscado.exibeLivro());
Aqui é uma ótima questão. Esse é um ponto de pura visualizaçao das infos do livros. A responsabilidade do formato de exibição está mais para o main do que para o livro em si. Já que este mesmo livro pode ser exibido de diversas formas diferentes. Para este tipo de caso, por mais que ter um método dentro do livro operando sobre o estado faça sentido, eu sugiro você expor via getter as informações e deixar o ponto de exibição decidir. Claro, só cria getter para o que precisa ser exibido :).

2020-03-11 19:01 UTC, danigfavero commented on Livros.java
> +		for (Livro livro : livros) {
Pensei sobre e acho que ficaria mais elegante mesmo... Só estou pensando em tudo o que eu teria que reimplementar. É um bom momento pra isso?

2020-03-11 19:06 UTC, asouza commented on Livros.java
> +		for (Livro livro : livros) {
Este é o momento. Testar, talvez errar, entender o motivo e fazer de novo :). Experimente livremente.

2020-03-12 10:53 UTC, asouza approved these changes
Massa! Você ta voando!

2020-03-12 16:11 UTC, merged