Exibir os itens de forma única e com suas respectivas quantidades
danigfavero/nossa-casa-codigo pull request #9
Opened 2020-03-13 19:55 UTC by danigfavero

Adiciona a feature ao carrinho de exibir itens de forma única, mostrando a quantidade adquirida de cada item e permitindo edição da quantidade de itens.

2020-03-14 00:34 UTC, asouza requested changes

2020-03-14 00:34 UTC, asouza commented on Carrinho.java
>  	public static BigDecimal totalProduto(BigDecimal preco, int quantidade) {
Essas informações que você recebe como argumento já existem dentro da própria classe carrinho :). A ideia é que seja conta seja feita em função do estado do carrinho e não através dos parâmetros aqui.

2020-03-14 00:34 UTC, asouza commented on Carrinho.java
> +        this.totalDoCarrinho = totalDoCarrinho.add(total);
Por conta de manter o valor do carrinho num atributo, você precisa atualizar este valor a cada alteração. E se você não precisasse manter essa informação num atributo...

2020-03-16 18:17 UTC, danigfavero commented on Carrinho.java
>  	public static BigDecimal totalProduto(BigDecimal preco, int quantidade) {
A ideia dessa função seria mais uma coisa estática pra eu não precisar ficar escrevendo código pra conseguir o total do produto, dado que eu não guardo a quantidade do Livro no objeto Livro. Se essa conta fosse feita em função do estado do carrinho, eu teria que armazenar o totalProduto em cada objeto ou guardar essa informação extra num outro atributo do carrinho (tipo um vetor)...
Não sei se deu pra entender direito, mas o que você sugeriria que eu fizesse?

2020-03-17 00:47 UTC, asouza requested changes

2020-03-17 00:47 UTC, asouza commented on Carrinho.java
> +    public static BigDecimal totalProduto(BigDecimal preco, int quantidade) {
Minha sugestão aqui é: o mapa estabelecendo a relação entre produto e quantidade tira a sua possibilidade de fazer essa conta dentro do "produto adicionado no carrinho". Acho que chegou a hora de você ter uma abstração que representa o item no carrinho :).

2020-03-17 00:47 UTC, asouza commented on Carrinho.java
> +    public static BigDecimal totalProduto(BigDecimal preco, int quantidade) {
Neste caso aqui até o nome do método pode ser um sinal para você.

2020-03-18 09:48 UTC, asouza requested changes

2020-03-18 09:48 UTC, asouza commented on Carrinho.java
> +            itemAntigo.setQuantidade(itemAntigo.getQuantidade() + 1);
*A sua api deve deixar claro o caminho que deve ser seguido pelo ponto do código que decide usá-la. Não espere que ninguém lembre de invocar nada. Faça de tudo para gerar obrigações. Quanto mais específico é seu código, menos democrático ele é.*

Opa, aqui é um ponto legal de abstração. Percebe que você passa como argumento o estado do item para um método do próprio item? Se o estado já está lá dentro e se você já sabe que é para acrescentar um, pq não deixar um método mais direto?

2020-03-18 09:48 UTC, asouza commented on Item.java
> +        return getPrecoUnidade().multiply(new BigDecimal(getQuantidade()));
excelente!

2020-03-18 13:21 UTC, asouza approved these changes

2020-03-18 13:21 UTC, asouza commented on Carrinho.java
> +            itemAntigo.incrementaQuantidade();
massa! Restrição é bom para o andamento do projeto. Ninguém mexe na quantidade que não seja para aumentar +1

2020-03-18 13:21 UTC, asouza commented on Item.java
>      public void setQuantidade(int quantidade) {
aqui pode remover

2020-03-18 13:25 UTC, danigfavero commented on Item.java
>      public void setQuantidade(int quantidade) {
mas eu uso o `setQuantidade()` no `edita()`

2020-03-18 13:52 UTC, merged